### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by NullCode1337** [AstraaDev/Discord-Find-My-Token#1]
bruh literally skidded wodxgod's grabber

atleast give him credits

**Comment by AstraaDev** [comment]
Hey NullCode, I just went to see this "Wodxgod".
Indeed his Token Grabber script looks like the one in 1 point. The way of token (but this one is the same in 80% of the scripts). 
Our 2 scripts don't even do the same thing... His grabs the tokens and sends them to a WebHook while mine just creates a txt file.

**Comment by NullCode1337** [comment]
yes they don't do the same thing
but the grabbing mechanism itself looks awfully similar

even the functions and stuff are the same yk

**Comment by AstraaDev** [comment]
Yes I know what you mean after that it's a script that I made a long time ago but I didn't publish it right away so it's possible that I was inspired by it but I really don't remember it.
